version: "3.9"

services:
  python-service:
    build: ./python-service
    env_file:
      - ./python-service/.env
    ports:
      - "8001:8001"
    restart: unless-stopped

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - python-service
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"   # nếu FE build production bằng nginx thì đổi thành "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
